---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: gems-src-in
outputs:
  - name: gems-src-out
run:
  path: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/update-gems.sh
