---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: dummy-release
  - name: stemcell
  - name: terraform
  - name: director-deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/deploy-dummy-release-multiple-manual-networks.sh
params:
  bosh_vcap_password:         ""
  v3_e2e_private_key_data:     ""
  stemcell_name:               ""
  instance_flavor:             ""
  delete_deployment_when_done: "true"
