---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: terraform
outputs:
  - name: deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/deploy-old-director.sh
params:
  BOSH_INIT_LOG_LEVEL:                    warn
  distro:                                 replace-me
  director_ca:                            replace-me
  director_ca_private_key:                replace-me
  bosh_openstack_ca_cert:                 replace-me
  v3_e2e_private_key_data:                replace-me
  old_bosh_release_version:               replace-me
  old_bosh_release_sha1:                  replace-me
  ci_bosh_admin_password:                 replace-me
  ci_v3_e2e_flavor:                       replace-me
  ci_v3_e2e_connection_timeout:           replace-me
  ci_v3_e2e_read_timeout:                 replace-me
  ci_v3_e2e_state_timeout:                replace-me
  ci_v3_e2e_write_timeout:                replace-me
  ci_v3_e2e_bosh_registry_port:           replace-me
  ci_v3_e2e_api_key:                      replace-me
  ci_v3_e2e_auth_url:                     replace-me
  ci_v3_e2e_project:                      replace-me
  ci_v3_e2e_domain:                       replace-me
  ci_v3_e2e_username:                     replace-me
  ci_time_server_1:                       replace-me
  ci_time_server_2:                       replace-me
  ci_old_openstack_cpi_release_version:   replace-me
  ci_old_openstack_cpi_release_sha1:      replace-me
  ci_old_bosh_stemcell_name:              replace-me
  ci_old_bosh_stemcell_version:           replace-me
  ci_old_bosh_stemcell_sha1:              replace-me
