---
jobs:
  - name: auto-update
    serial: true
    plan:
      - aggregate:
        - {trigger: false,  get: bosh-cpi-src-in,       tags: ['blue-box'], timeout: 2h}
        - {trigger: true,   get: pipeline-time-trigger, tags: ['blue-box'], timeout: 2h}

      - task: auto-update-gems
        tags: ['blue-box']
        timeout: 2h
        file: bosh-cpi-src-in/ci/pipelines/auto-update/tasks/auto-update-gems.yml

resources:
  - name: bosh-cpi-src-in
    type: git
    tags: ['blue-box']
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: master
      ignore_paths:
        - releases/bosh-openstack-cpi/**
        - .final_builds/**
        - docs/**
        - README.md

  - name: pipeline-time-trigger
    type: time
    tags: ['blue-box']
    source:
      interval: 24h
