---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pull-request
  tags: [blue-box]
  type: pull-request
  source:
    repo: cloudfoundry-incubator/bosh-openstack-cpi-release
    access_token: {{github-access-token}}

jobs:
- name: unit-test
  public: true
  tags: [blue-box]
  plan:
  - get: pull-request
    tags: [blue-box]
    trigger: true
    version: every
  - put: pull-request
    tags: [blue-box]
    params: {path: pull-request, status: pending}
  - task: test
    tags: [blue-box]
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: boshcpi/openstack-cpi-release
      inputs:
      - name: pull-request
      run:
        path: sh
        args:
        - -c
        - "cd pull-request/src/bosh_openstack_cpi && bundle install && bundle exec rspec spec/unit/*"
    on_failure:
      put: pull-request
      tags: [blue-box]
      params: {path: pull-request, status: failure}
    on_success:
      put: pull-request
      tags: [blue-box]
      params: {path: pull-request, status: success}